name: CI

on:
  pull_request:
    paths:
      - "otv/**"
      - "meson.build"
      - "meson_options.txt"
      - ".github/workflows/**"
  push:
    branches: [main]
    paths:
      - "otv/**"
      - "meson.build"
      - "meson_options.txt"
      - ".github/workflows/**"
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Get latest OpenTraceCapture release
        id: otc-release
        uses: actions/github-script@v7
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: 'OpenTraceLab',
              repo: 'OpenTraceCapture'
            });
            // Sort by created_at descending to get most recent
            const sortedReleases = releases.data.sort((a, b) => 
              new Date(b.created_at) - new Date(a.created_at)
            );
            const latestTag = sortedReleases[0].tag_name;
            core.setOutput('tag', latestTag);
            core.info(`Using OpenTraceCapture ${latestTag}`);

      # Linux cache
      - name: Cache (Linux)
        if: runner.os == 'Linux'
        uses: actions/cache@v4
        with:
          path: |
            $HOME/.cache/ccache
            $HOME/.cache/meson
          key: linux-${{ hashFiles('**/meson.build','**/meson_options.txt') }}
          restore-keys: linux-

      # macOS cache
      - name: Cache (macOS)
        if: runner.os == 'macOS'
        uses: actions/cache@v4
        with:
          path: |
            $HOME/.cache/ccache
            $HOME/.cache/meson
          key: mac-${{ hashFiles('**/meson.build','**/meson_options.txt') }}
          restore-keys: mac-

      # Windows cache
      - name: Cache (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\.ccache
            C:\Users\runneradmin\AppData\Local\meson
          key: win-${{ hashFiles('**/meson.build','**/meson_options.txt') }}
          restore-keys: win-

      - name: Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build pkg-config gcc g++ ccache python3-pip \
            libglib2.0-dev libglibmm-2.4-dev libusb-1.0-0-dev libzip-dev libftdi1-dev \
            libserialport-dev libhidapi-dev libieee1284-3-dev \
            qt6-base-dev qt6-base-dev-tools libqt6svg6-dev qt6-tools-dev \
            libboost-serialization-dev libboost-system-dev libboost-stacktrace-dev \
            doxygen
          pip3 install --user meson
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          echo "/usr/lib/ccache" >> "$GITHUB_PATH"
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH" >> "$GITHUB_ENV"
          mkdir -p "$HOME/.cache/ccache" "$HOME/.cache/meson"

      - name: Install OpenTraceCapture (Linux)
        if: runner.os == 'Linux'
        run: |
          wget -q https://github.com/OpenTraceLab/OpenTraceCapture/releases/download/${{ steps.otc-release.outputs.tag }}/opentracecapture-linux.tar.gz
          sudo tar xzf opentracecapture-linux.tar.gz -C /usr
          sudo ldconfig

      - name: Install OpenTraceDecode (Linux)
        if: runner.os == 'Linux'
        run: |
          wget -q https://github.com/OpenTraceLab/OpenTraceDecode/releases/download/v0.1.0-alpha.1/opentracedecode-linux.tar.gz
          sudo tar xzf opentracedecode-linux.tar.gz -C /usr
          sudo ldconfig

      - name: macOS deps
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install meson ninja pkg-config ccache glib glibmm libusb libzip libftdi \
            hidapi libserialport qt6 boost doxygen
          echo "$(brew --prefix ccache)/libexec" >> "$GITHUB_PATH"
          echo "XDG_CACHE_HOME=$HOME/.cache"   >> "$GITHUB_ENV"
          echo "CCACHE_DIR=$HOME/.cache/ccache" >> "$GITHUB_ENV"
          mkdir -p "$HOME/.cache/ccache" "$HOME/.cache/meson"

      - name: Install OpenTraceCapture (macOS)
        if: runner.os == 'macOS'
        run: |
          wget -q https://github.com/OpenTraceLab/OpenTraceCapture/releases/download/${{ steps.otc-release.outputs.tag }}/opentracecapture-macos.tar.gz
          sudo tar xzf opentracecapture-macos.tar.gz -C /usr/local

      - name: Install OpenTraceDecode (macOS)
        if: runner.os == 'macOS'
        run: |
          wget -q https://github.com/OpenTraceLab/OpenTraceDecode/releases/download/v0.1.0-alpha.1/opentracedecode-macos.tar.gz
          sudo tar xzf opentracedecode-macos.tar.gz -C /usr/local

      - name: MSYS2 setup
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-ccache
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-glibmm
            mingw-w64-x86_64-libusb
            mingw-w64-x86_64-libzip
            mingw-w64-x86_64-libftdi
            mingw-w64-x86_64-libserialport
            mingw-w64-x86_64-hidapi
            mingw-w64-x86_64-qt6
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-doxygen

      - name: Install OpenTraceCapture (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          wget -q https://github.com/OpenTraceLab/OpenTraceCapture/releases/download/${{ steps.otc-release.outputs.tag }}/opentracecapture-windows.tar.gz
          tar xzf opentracecapture-windows.tar.gz -C /mingw64

      - name: Install OpenTraceDecode (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          wget -q https://github.com/OpenTraceLab/OpenTraceDecode/releases/download/v0.1.0-alpha.1/opentracedecode-windows.tar.gz
          tar xzf opentracedecode-windows.tar.gz -C /mingw64

      - name: Build & test (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          meson setup build --buildtype=release
          meson configure build
          meson compile -C build
          meson test -C build --print-errorlogs

      - name: Build & test (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          export CCACHE_DIR=/c/Users/runneradmin/.ccache
          export XDG_CACHE_HOME=/c/Users/runneradmin/AppData/Local
          mkdir -p "$CCACHE_DIR"
          meson setup build --buildtype=release
          meson configure build
          meson compile -C build
          meson test -C build --print-errorlogs
